---

repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.4.0  # release tag from https://github.com/ansible-community/ansible-lint/releases/
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        exclude: (^travis.yml$)
