---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include {{ cookiecutter.role_name }}"
      ansible.builtin.include_role:
        name: "{{ cookiecutter.github_username }}.{{ cookiecutter.role_name }}"
